Models/Comment.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventureWorksWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int CommentID { get; set; }
        public string User { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public Nullable<int> PhotoID { get; set; }
    
        public virtual Photo Photo { get; set; }
        public virtual User User1 { get; set; }
    }
}

Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using AdventureWorksWebApp.Models;
using AdventureWorksWebApp.Utils;

namespace AdventureWorksWebApp.Controllers
{
    public class CommentsController : Controller
    {
        private AdventureWorks_DBEntities db = new AdventureWorks_DBEntities();

        // GET: Comments
        public ActionResult Index()
        {
            var comment = db.Comment.Include(c => c.User1);
            return View(comment.ToList());
        }

        // GET: Comments/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comment.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        // GET: PhotosComments/New/5
        public ActionResult NewComment(int? id)
        {
            ViewBag.Username = User.Identity.Name;
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Photo photo = db.Photo.Find(id);
            if (photo == null)
            {
                return HttpNotFound();
            }
            Comment comment = new Comment();
            comment.PhotoID = photo.PhotoID;
            return View(comment);
        }

        // GET: Comments/Create
        public ActionResult Create()
        {
            ViewBag.PhotoID = new SelectList(db.Photo, "PhotoID", "Title");
            ViewBag.User = new SelectList(db.User, "User1", "Name");
            return View();
        }

        // POST: Comments/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CommentID,User,Subject,Body,PhotoID")] Comment comment)
        {
            comment.User =User.Identity.Name;
            if (ModelState.IsValid)
            {
                db.Comment.Add(comment);
                db.SaveChanges();
                /*return RedirectToAction("Index");*/
                string mensaje = String.Format("../Photos/Details/{0}", comment.PhotoID);
                return RedirectToAction(mensaje);
            }
            ViewBag.PhotoID = new SelectList(db.Photo, "PhotoID", "Title", comment.PhotoID);
            ViewBag.User = new SelectList(db.User, "User1", "Name", comment.User);
            return View(comment);
            
        }

        // GET: Comments/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comment.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            ViewBag.PhotoID = new SelectList(db.Photo, "PhotoID", "Title", comment.PhotoID);
            ViewBag.User = new SelectList(db.User, "User1", "Name", comment.User);
            return View(comment);
        }

        // POST: Comments/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CommentID,User,Subject,Body,PhotoID")] Comment comment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(comment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Edit");
            }
            ViewBag.PhotoID = new SelectList(db.Photo, "PhotoID", "Title", comment.PhotoID);
            ViewBag.User = new SelectList(db.User, "User1", "Name", comment.User);
            return View(comment);
        }

        // GET: Comments/Delete/5
        public ActionResult Delete(int? id)
        {
            ViewBag.Username = User.Identity.Name;
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comment.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        // POST: Comments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Comment comment = db.Comment.Find(id);
            db.Comment.Remove(comment);
            db.SaveChanges();
            string mensaje = String.Format("../Photos");
            return RedirectToAction(mensaje);
        }


        public ActionResult GetImage(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var imgByte = db.Photo.Find(id).PhotoFile;

            if (imgByte == null)
            {
                return HttpNotFound();
            }
            return new FileContentResult(imgByte, "image/png");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/PhotosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AdventureWorksWebApp.Models;
using AdventureWorksWebApp.Utils;
using log4net;

namespace AdventureWorksWebApp.Controllers
{
    public class PhotosController : BaseController
    {
        private readonly ILog log = LogManager.GetLogger(typeof(PhotosController));

        private AdventureWorks_DBEntities db = new AdventureWorks_DBEntities();

        // GET: Photos
        public ActionResult Index()
        {
            var photo = db.Photo.Include(p => p.User);
            return View(photo.ToList());
        }


        // GET: Photos
        public ActionResult LatestPhotos()
        {
            var photo = db.Photo.Include(p => p.User);
            photo = photo.OrderByDescending(r => r.CreatedDate).Take(4);
            return View(photo.ToList());
        }
        public ActionResult Carousel(int? id)
        {
            var photo = db.Photo.Include(p => p.User);
            return View(photo.ToList());
        }

        // GET: Photos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Photo photo = db.Photo.Find(id);
            if (photo == null)
            {
                return HttpNotFound();
            }
            return View(photo);
        }

        // GET: Photos/Create
        public ActionResult Create()
        {
            ViewBag.Owner = new SelectList(db.User, "User1", "Name");
            return View();
        }

        // POST: Photos/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create([Bind(Include = "Title,PhotoFile,Description")] Photo photo, HttpPostedFileBase imgFile)
        {
            if (ModelState.IsValid && imgFile != null)
            {
                if (imgFile.ContentLength > Constants.MAXIMUM_ALLOWED_FILE_UPLOAD)
                {
                    ViewBag.ErrorMessage = "Este archivo supera el tamaño máximo permitido de 4MB.";
                    return View();
                }

                if (!Constants.ALLOWED_EXTENSIONS.Contains(Path.GetExtension(imgFile.FileName).ToLower()))
                {
                    ViewBag.ErrorMessage = "Formato de archivo inválido. Solo se permiten archivos con extensión .jpeg.";
                    return View();
                }

                var imgByte = new byte[imgFile.ContentLength];
                imgFile.InputStream.Read(imgByte, 0, imgFile.ContentLength);
                photo.PhotoFile = imgByte;
                photo.CreatedDate = DateTime.Today;
                photo.Owner = User.Identity.Name;

                db.Photo.Add(photo);
                db.SaveChanges();
                return RedirectToAction("Index");

            }

            return View(photo);
        }

        [Authorize]
        // GET: Photos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Photo photo = db.Photo.Find(id);
            if (photo == null)
            {
                return HttpNotFound();
            }
            ViewBag.Owner = new SelectList(db.User, "User1", "Name", photo.Owner);
            return View(photo);
        }

        // POST: Photos/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PhotoID,Title,PhotoFile,Description,CreatedDate,Owner")] Photo photo)
        {
            if (ModelState.IsValid)
            {
                db.Entry(photo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Owner = new SelectList(db.User, "User1", "Name", photo.Owner);
            return View(photo);
        }



        // GET: Photos/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Photo photo = db.Photo.Find(id);
            if (photo == null)
            {
                return HttpNotFound();
            }
            return View(photo);
        }

        [Authorize]
        // POST: Photos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Photo photo = db.Photo.Find(id);
            db.Photo.Remove(photo);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult SaveImagen(int? id, HttpPostedFileBase imgFile)
        {
            Photo photo = db.Photo.Find(id);

            if (imgFile != null)
            {
                var imgByte = new byte[imgFile.ContentLength];
                imgFile.InputStream.Read(imgByte, 0, imgFile.ContentLength);
                photo.PhotoFile = imgByte;
                db.Entry(photo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(photo);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Comments/Create.cshtml
@model AdventureWorksWebApp.Models.Comment

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Comment</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <img src="@Url.Content("~/Comments/GetImage")" height="200" class="img-thumbnail" />
    <div class="form-group">
        @Html.LabelFor(model => model.User, "User", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("User", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.User, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Subject, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Subject, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Subject, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Body, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Body, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PhotoID, "PhotoID", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("PhotoID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.PhotoID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Comments/Delete.cshtml
@model AdventureWorksWebApp.Models.Comment

@{
    ViewBag.Title = "Delete";
}
<section class="justify-content-center items-center align-content-center align-items-center">
    <div class="card my-4 p-4" style="max-width: 1000px; min-width: 500px; display: block; width: 50%; margin: 0 auto;">
        <h2>Delete</h2>

        <h3>Are you sure you want to delete this?</h3>
        <div>
            <h4>Comment</h4>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Subject)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Subject)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Body)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Body)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.User1.Name)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.User1.Name)
                </dd>

            </dl>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            <a href='@Url.Action("Details", "Photos", new { id = @Model.PhotoID })'>
                Back to photo
            </a>

        </div>
            }
        </div>
    </div>

</section>

Views/Comments/Details.cshtml
@model AdventureWorksWebApp.Models.Comment

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Comment</h4>
    <hr />
    <dl class="dl-horizontal">
        <img src="@Url.Content("~/Comments/GetImage/" + Model.PhotoID)" height="200" class="img-thumbnail" />
        <dt>
            @Html.DisplayNameFor(model => model.Subject)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Subject)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Body)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Body)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User1.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User1.Name)
        </dd>


        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
        }

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.CommentID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Comments/Edit.cshtml
@model AdventureWorksWebApp.Models.Comment

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Comment</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.CommentID)
    @Html.HiddenFor(model => model.User1)
    @Html.HiddenFor(model => model.CommentID)
    @Html.HiddenFor(model => model.PhotoID)
    <img src="@Url.Content("~/Comments/GetImage/" + Model.PhotoID)" height="200" class="img-thumbnail" />
    <div class="form-group">
        @Html.LabelFor(model => model.Subject, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Subject, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Body, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Body, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Comments/Index.cshtml
@model IEnumerable<AdventureWorksWebApp.Models.Comment>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Subject)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Body)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.User1.Name)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Subject)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Body)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.User1.Name)
            </td>
            
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.CommentID }) |
                @Html.ActionLink("Details", "Details", new { id = item.CommentID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.CommentID })
            </td>
        </tr>
    }

</table>

Views/Comments/NewComment.cshtml
@model AdventureWorksWebApp.Models.Comment

@{
    ViewBag.Title = "New comment";
}



<section class="justify-content-center items-center align-content-center align-items-center">
    <div class="card my-4 p-4" style="max-width: 1000px; min-width: 500px; display: block; width: 50%; margin: 0 auto;">
        <h2>New comment</h2>

        <div class="mb-4">
            <a href="@Url.Action("Details", "Photos", new { id = @Model.PhotoID })" class="btn btn-secondary">Back to photo</a>
        </div>
        @using (Html.BeginForm("Create", "Comments", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(model => model.PhotoID)
            <div class="form-horizontal">
                <h4>Comment</h4>
                <img src='@Url.Action("GetImage", "Comments", new { id = Model.PhotoID })' height="200" class="img-thumbnail" alt="photo - @Model.PhotoID" />


                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group">
                    @Html.LabelFor(model => model.Subject, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Subject, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Subject, "", new { @class = "text-danger" })
                    </div>
                </div>


                <!-- Cuerpo -->
                <div class="form-group mb-4">
                    @Html.LabelFor(model => model.Body, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div>
                        @Html.TextAreaFor(model => model.Body, htmlAttributes: new { @class = "form-control", rows = "4", @required = "true" })
                        @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Comment" class="btn btn-outline-secondary" />
                    </div>
                </div>
            </div>
        }
    </div>

</section>